### ISSUE TITLE
Probe failures on heavy usage of dashboard(?)

### ISSUE THREAD

**Issue by jgrau** [bensheldon/good_job#1068]
Hi @bensheldon 

This is more of a question than an issue. We're using good_job in a kubernetes environment with lots of success. We experiencing that the health check fails a couple of times a day. A few days ago I was browsing the good job dashboard and noticed that at the same time, the healthcheck failed and kubernetes restarted the workers. The dashboard does seem to perform some very slow queries but on the other hand the dashboard is served by the webserver pods and not the worker pods. 

Anyways: I just wanted to quickly check in to see if this made any sense to you before I go on a wild-goose chase... :)

**Comment by bensheldon** [comment]
hmmm, I think that might be a coincidence, but I bet we would learn something interesting if it wasn't! 🤔 

What endpoint (started/connected?) are you using for your healtheck?

https://github.com/bensheldon/good_job/blob/c0e14082cd697465eb7148c3f88b38bcebac07c1/lib/good_job/probe_server.rb#L39C22-L40

The only way I could imagine right now the Dashboard affecting the probe server is if one of the dashboard's queries was locking a table, and then that was blocking.

...or if the long-running LISTEN database connection was disconnected, there would be a slight bit of time before it reconnected that _does_ change the `listening?` method from true to false. If the probe got hit right then it would be a failure. Hmmmm.

Do you have logs? Are you seeing `"Notifier unsubscribed with UNLISTEN"`? 

This makes me think there should be a period of like "successfully listened previously and is now reconnecting for N seconds)" that would not trip that health check. (assuming that is what you're experiencing)

**Comment by jgrau** [comment]
> hmmm, I think that might be a coincidence, but I bet we would learn something interesting if it wasn't! 🤔
> 
> What endpoint (started/connected?) are you using for your healtheck?

Yes, this is the relevant kubernetes configuration:

```yaml
          startupProbe:
            httpGet:
              path: '/status/started'
              port: probe-port
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: '/status/connected'
              port: probe-port
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
```

> 
> https://github.com/bensheldon/good_job/blob/c0e14082cd697465eb7148c3f88b38bcebac07c1/lib/good_job/probe_server.rb#L39C22-L40
> 
> The only way I could imagine right now the Dashboard affecting the probe server is if one of the dashboard's queries was locking a table, and then that was blocking. Edit: I don't think this is likley.
> 
> EDIT: the following is not related to the dashboard, but I imagine is much more likely the problem.
> 
> ...or if the long-running LISTEN database connection was disconnected, there would be a slight bit of time before it reconnected that _does_ change the `listening?` method from true to false. If the probe got hit right then it would be a failure. Hmmmm.
> 
> Do you have logs? Are you seeing `"Notifier unsubscribed with UNLISTEN"`?

Yes, I am seeing that. 23 entries within the last 24 hours.

> 
> This makes me think there should be a period of like "successfully listened previously and is now reconnecting for N seconds" that would not trip that health check. (assuming that is what you're experiencing)

Do I understand correctly that it's expected that the LISTEN database connection is disconnected and the worker will automatically just reconnect? If so, then it does sound like a good idea that doesn't make the healthcheck fail. Or alternatively document that that is expected - I believe it can then be solved by setting `failureThreshold: 2`(?)
