### ISSUE TITLE
Spanish translation while on the dashboard displays hashes instead of the job status name

### ISSUE THREAD

**Issue by ronb54** [bensheldon/good_job#1304]
Hello! 👋

I recently started using this gem for my project. While clicking around on the dashboard after initial setup, I toggled between translations and noticed hashes were being displayed on the job status names. A picture's worth a thousand words they say, so here's what I mean:
<img width="2051" alt="Screenshot 2024-03-29 at 03 08 32" src="https://github.com/bensheldon/good_job/assets/35236981/96a3f441-5e54-4cb9-88f6-df0e18a5dbb1">

See it here on the demo app as well: https://goodjob-demo.herokuapp.com/good_job/jobs?locale=es&state=scheduled.

Looks like a simple change to handle hashes in the shared `_filter` partial.  And the `es` locale seems to be the only one that has multiple translations.
```
    status:
      discarded:
        one: Descartada
        other: Descartadas
      queued:
        one: Encolada
        other: Encoladas
  .....
```
All the other locales are defined with a simple string (e.g. `de`):
```
    status:
      discarded: Ausrangiert
      queued: In der Warteschlange
      retried: Wiederholt
```

I could do a quick PR if this hasn't been PR'd already. Let me know.

I also don't have the context for why `es` has the nested config. Perhaps there's a future plan for using the alternate translation?
