### ISSUE TITLE
Job stuck in queued state and never picked up

### ISSUE THREAD

**Issue by luizkowalski** [bensheldon/good_job#1590]
Hey 👋🏻 

Every now and then, I see a weird issue, just in development: a job gets scheduled but never picked up. 

I have an endpoint that schedules a job when gets a callback:

```ruby

 def show
  client.tap { it.code = params[:code] }

  raw_token = client.fetch_access_token!

  account = Account.from_token(raw_token, current_user: Current.user)
  account.sync # Here is where a job gets enqueued

  store_and_redirect(account.user)
rescue ActiveRecord::RecordInvalid => e
  redirect_to root_path, flash: { alert: e.message }
end
```

Sometimes, without any specific trigger or event, the job gets queued but doesn't get picked up:

<img width="1007" alt="Image" src="https://github.com/user-attachments/assets/5375defb-a32b-4bf9-a570-502acafde823" />

This one is sitting in the queue for 5 minutes.

I also noticed that when this happens, it's like the process enters a deadlock state or something. I said this because it stops pinging:

<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/f220834c-8894-458f-a0f6-cb099512bd11" />

and when I stop the process, it actually has to get killed

```
worker    | Interrupting...
...
worker    | Killing...
```

while when everything is fine, it just exits

```
worker    | [GoodJob] Notifier unsubscribed with UNLISTEN                                                                                                                                                 worker    | [GoodJob] [98819] GoodJob shutting down scheduler...                                                                                                                                          worker    | [GoodJob] [98819] GoodJob scheduler is shut down.                                                                                                                                             worker    | [GoodJob] [98819] GoodJob shutting down scheduler...
worker    | [GoodJob] [98819] GoodJob scheduler is shut down.
worker    | [GoodJob] [98819] GoodJob shutting down scheduler...
worker    | [GoodJob] [98819] GoodJob scheduler is shut down.                                                                                                                                             worker    | [GoodJob] [98819] GoodJob shutting down scheduler...
worker    | [GoodJob] [98819] GoodJob scheduler is shut down.                                                                                                                                             worker    | Exited with code 0
```

I'm not sure if this rings any bell but I'm seeing this in two different machines, in dev only..

Here is my config:

```ruby
# frozen_string_literal: true

Rails.application.configure do
  config.good_job = Rails.application.config_for(:good_job).merge(
    on_thread_error: ->(exception) { Rails.error.report(exception) }
  )
end
```

```yaml
default: &default
  queues: urgent:10;default:5;low_priority:3;*
  max_threads: <%= ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i %>
  execution_mode: external
  enable_cron: <%= ENV["CRON_ENABLED"] == "1" %>

production:
  <<: *default
  queues: urgent:5;default:3;low_priority:2;*
  cron:
    query_stats:
      cron: "*/30 * * * *" # every 30 minutes
      class: "CaptureQueryStatsJob"
    refresh_tokens:
      cron: "0 */2 * * *" # every 2 hours
      class: "Accounts::RefreshTokensJob"
    renew_expired_channels:
      cron: "0 3 * * *" # every day at 3am
      class: "Calendars::RenewExpiredChannelsJob"

development:
  <<: *default

test:
  <<: *default
```

Running Rails from `main` branch and the latest Good Job (4.8.2 as of now). Both machines being Mac, one is a M1 and another M2 Pro. I start my dev env with Overmind:

```sh
#!/usr/bin/env sh

if ! overmind --version; then
  echo "Installing overmind..."
  brew install overmind
fi

# Default to port 3000 if not specified
export PORT="${PORT:-3000}"

echo "Cleaning logs"

rm -rf log/*.log

OVERMIND_SKIP_ENV=1 exec overmind start -f Procfile.dev "$@"
```

and my Procfile looks like this
```
web: bin/rails server
js: bun run build --watch
css: bun run build:css --watch
worker: bin/good_job start
stripe_fw: stripe listen --forward-to http://127.0.0.1:3000/pay/webhooks/stripe
```

I also don't know exactly what triggers this, I'm trying to reproduce and find something but just want to put this out in case you know something.
