### ISSUE TITLE
Jobs stuck in the unfinished state

### ISSUE THREAD

**Issue by MatUrbanski** [bensheldon/good_job#448]
Hi, I'm using `good_job` in the Ruby on Rails 6.0.4.1 app that uses Ruby 2.7.2. Application is deployed to the AWS using Fargate and uses AWS RDS PostgreSQL. After the deployment application is working as expected but at some point, all new jobs are stuck with unfinished state and `good_job` is not processing them. Here is my configuration:

config/database.yml:
```
default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
  encoding: unicode

development:
  <<: *default
  database: test_app_development

test:
  <<: *default
  database: test_app_test

non_production:
  <<: *default
  database: test_app_non_production
  host: <%= ENV['TEST_APP_NONPROD_DATABASE_HOST'] %>
  username: <%= ENV['TEST_APP_NONPROD_DATABASE_USER'] %>
  password: <%= ENV['TEST_APP_NONPROD_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: test_app_production
  host: <%= ENV['TEST_APP_DATABASE_HOST'] %>
  username: <%= ENV['TEST_APP_DATABASE_USER'] %>
  password: <%= ENV['TEST_APP_DATABASE_PASSWORD'] %>
```

/config/initializers/good_job.rb
```
# Keeps job records in your database even after jobs are completed.
GoodJob.preserve_job_records = true

GoodJob::Engine.middleware.use(Rack::Auth::Basic) do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(ENV['GOOD_JOB_USERNAME'], username) &&
    ActiveSupport::SecurityUtils.secure_compare(ENV['GOOD_JOB_PASSWORD'], password)
end
```

Any idea what can cause issue like that?
