### ISSUE TITLE
Configuration for PG Schema Other Than Public

### ISSUE THREAD

**Issue by ylg** [bensheldon/good_job#774]
tldr; Is there a specific way to setup for GoodJob tables not in Postgres public, or should it just work?

I imagine I'm making a rookie mistake here, as we've used not used ActiveRecord in any project since the late 2000s. Only pulling it in to support GoodJob (a testament to GoodJob's goodness as AR is reviled here).  Anyway, when GoodJob schema objects are not in PG's public schema, GoodJob (AR) seems unable to find them. Normally we set schema search paths on the DB connection URL, but that does not seem to work here. I also tried what seems to be the Rails/AR "way" of using a YAML config, like so:

```yaml
development: &default
  adapter: postgresql
  host: localhost
  database: some_db
  username: some_user
  password: some_pass
  schema_search_path: 'other_schema,public'

  [...]
```

But no joy for GoodJob--though a very quick HelloWorld AR model seemed OK. Perhaps GoodJob is using it's own connection logic that doesn't utilize search_path. But, again, my first guess would be a mistake I've made, so I mainly want to confirm I should keep looking, i.e., this a fight with AR not with GJ.
